from enum import Enum, unique

@unique
class CONSTANTS(Enum):
    # 以下常量用于设置store里面的键值对。
    OPENFED_IDENTIFY = "OPENFED_IDENTIFY"
    OPENFED_STATUS = "OPENFED_STATUS"
    OPENFED_KING_SYS_INFO = "OPENFED_KING_SYS_INFO"
    OPENFED_KING_GPU_INFO = "OPENFED_KING_GPU_INFO"
    OPENFED_QUEUE_SYS_INFO = "OPENFED_QUEUE_SYS_INFO"
    OPENFED_QUEUE_GPU_INFO = "OPENFED_QUEUE_GPU_INFO"

    # 一些其他常量
    OPENFED_TASK_INFO = "OPENFED_TASK_INFO"